replicaCount: 1
containerPort: 80
NodePort: 30080

image:
  repository: nginx
  tag: "latest"
  pullPolicy: Always


service: 
  type: ClusterIP
  port: 80

ingress: 
  enabled: false

namespace: demo

resources: {}

nodeSelector: {}

  